package by.training.finalproject.controller.command;

public enum CommandName {
    SIGN_IN, SIGN_UP, GO_TO_SIGN_UP_PAGE, GO_TO_SIGN_IN_PAGE, GO_TO_HOME_PAGE, EN_US, RU_RU, LOGOUT, GO_TO_AD_PAGE,
    ADD_COMMENT, LIKE_AD, GO_TO_ADD_AD_PAGE, ADD_AD, GO_TO_USER_PROFILE_PAGE, DELETE_AD, GO_TO_EDIT_AD_PAGE, EDIT_AD,
    ADD_CATEGORY, DELETE_CATEGORY, EDIT_CATEGORY, GO_TO_TYPES_PAGE, GO_TO_USERS_PAGE, DELETE_USER, GO_TO_EDIT_USER_PAGE,
    EDIT_USER, DELETE_COMMENT, SEARCH_ADS, FILTER_ADS, WRONG_REQUEST
}
